# Generated by Django 5.1 on 2024-10-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsCategory', '0002_productcategory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
