# Generated by Django 5.1 on 2024-10-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductsItem', '0001_initial'),
        ('ShoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ShoppingCart.shoppingcart')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ProductsItem.productitem')),
            ],
        ),
    ]
