# Generated by Django 5.1 on 2024-10-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCartItem', '0002_shoppingcartitem_notes_shoppingcartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='qty',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
