# Generated by Django 5.1 on 2024-11-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0011_product_image_url'),
        ('ProductsCategory', '0003_productcategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applicable_to', models.CharField(blank=True, max_length=100, null=True)),
                ('user_group', models.CharField(blank=True, choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('customer', 'Customer'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=20, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductsCategory.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
