# Generated by Django 5.1 on 2024-10-17 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsItem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ProductsItem.productitem')),
            ],
        ),
    ]
