# Generated by Django 5.1 on 2024-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chat_attachments_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành')], default='new', max_length=15),
        ),
    ]
