# Generated by Django 5.1 on 2024-11-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_message_is_sent_message_status_notification_and_more'),
        ('SiteUser', '0009_siteuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='participants',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_sessions', to='SiteUser.siteuser'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_chat_session', to='SiteUser.siteuser'),
            preserve_default=False,
        ),
    ]
