# Generated by Django 5.1 on 2024-11-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_alter_review_options_remove_review_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
