# Generated by Django 5.1 on 2024-10-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='SiteUser.siteuser')),
            ],
        ),
    ]
