# Generated by Django 5.1 on 2024-10-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('SiteUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_method', models.CharField(max_length=100)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderstatus')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteUser.userpaymentmethod')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteUser.address')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='SiteUser.siteuser')),
            ],
        ),
    ]
