# Generated by Django 5.1 on 2024-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_productimage_image_productimage_url'),
        ('SiteUser', '0004_likedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='likedproduct',
            unique_together={('user', 'product')},
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('site_user',), name='unique_primary_address_per_user'),
        ),
    ]
