# Generated by Django 5.1 on 2024-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteUser', '0005_remove_siteuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
