# Generated by Django 5.1 on 2024-10-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
