# Generated by Django 5.1 on 2024-10-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_product_image_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.URLField(default='https://meatworld.com.vn/wp-content/uploads/anh-avatar-anime-2-1.jpg'),
            preserve_default=False,
        ),
    ]
