# Generated by Django 5.1 on 2024-10-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_productimage_image_productimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
