# Generated by Django 5.1 on 2024-10-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Louis Vuitton', max_length=255),
            preserve_default=False,
        ),
    ]
